### ISSUE TITLE
Warning: forced trusting untrusted contributions shown during installing 1.7.5

### ISSUE THREAD

**Issue by ytsuboi** [Seeed-Studio/ArduinoCore-samd#11]
"Warning: forced trusting untrusted contributions" on post_install.bat.
Windows 10 64bit, Arduino IDE 1.8.12 Windows Installer version.

**Comment by Pillar1989** [comment]
@ytsuboi  What does that mean? Where did it come from? Do we need to deal with it?

**Comment by ytsuboi** [comment]
@Pillar1989 Yes we need to fix it because users are not sure they could get ArduinoCore-samd installed properly or not. In addition, we are not sure it installed properly, aren't we? I don't know where it comes from. It wasn't happen on 1.7.3.
