### ISSUE TITLE
Arduino tone() function doesn't work with buzzer on Wio Terminal

### ISSUE THREAD

**Issue by technoblogy** [Seeed-Studio/ArduinoCore-samd#25]
The Wio Terminal has a buzzer on Arduino pin 12, but it doesn't seem to work with the Arduino **tone()** function.

For example, uploading the standard example file **toneMelody** and changing the first parameter of **tone()** to 12 doesn't produce any sound.

Any suggestions?

**Comment by Pillar1989** [comment]
Please update and retest it
https://github.com/Seeed-Studio/ArduinoCore-samd/commit/cbc482e046e64c870d02d8b30d8fbf7bc06fb8b4

**Comment by technoblogy** [comment]
Yes, it works nicely now - thanks!
