### ISSUE TITLE
Wio Terminal BCM14/15/18 Mapping

### ISSUE THREAD

**Issue by jhunacek** [Seeed-Studio/ArduinoCore-samd#27]
I think BCM14, BCM15, and BCM18 as defined in variant.h under wio_terminal point to the wrong pins.  I think they should be 40ul, 41ul, and 52ul respectively, instead of the current values of 41ul, 40ul, and 17ul.

**Comment by LynnL4** [comment]
Hi,
Thank you for your feedback, we have fixed this problem in branch [dev-1.7.9](https://github.com/Seeed-Studio/ArduinoCore-samd/tree/dev-1.7.9) and will release it in the near future.
