### ISSUE TITLE
the build script is broken and board definitions are missing for Seeed boards.

### ISSUE THREAD

**Issue by kazuhiko-hotta** [Seeed-Studio/ArduinoCore-samd#38]
The build script is broken, and board definitions are missing for Seeed boards.

In the build script, there are not names of Seeed boards.

https://github.com/Seeed-Studio/ArduinoCore-samd/blob/master/bootloaders/zero/build_all_bootloaders.sh

And, the board definitions are missing.

**Comment by Pillar1989** [comment]
You're right, the script came from the original repository and we didn't use it.
