### ISSUE TITLE
Seeed XIAO的睡眠模式示例中缺少RTCInt.h文件

### ISSUE THREAD

**Issue by XuyeZhang** [Seeed-Studio/ArduinoCore-samd#44]
WakeUpOnRTCInterrupt项目编译时提示缺少RTCInt.h文件

**Comment by sunkr1995** [comment]
遇到了同样的问题

**Comment by Pillar1989** [comment]
https://github.com/Seeed-Studio/Seeed_Arduino_RTC  这个仓库能解决你们的问题吗 ？  @sunkr1995  @XuyeZhang
