### ISSUE TITLE
Winterrupt.c: swapped lines lead to lost interrupts

### ISSUE THREAD

**Issue by FerGT50** [Seeed-Studio/ArduinoCore-samd#48]
While investigating about lost steps with rotary encoders, a possible bug was found in Winterrupt.c, leading to lost interrupts.

Sorry, don't know how to to a proper PR yet, please see:

https://github.com/luni64/EncoderTool/issues/2#issuecomment-831365667

**Comment by LynnL4** [comment]
Thanks!
