### ISSUE TITLE
Unable to build projects using Adafruit_USBD_HID

### ISSUE THREAD

**Issue by yamamaya** [Seeed-Studio/ArduinoCore-samd#50]
Unable to build projects using Adafruit_USBD_HID with Seeeduino XIAO.  It causes following error.
error: cannot declare variable 'usb_hid' to be of abstract type 'Adafruit_USBD_HID'

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

Do you still have this problem now?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
