### ISSUE TITLE
Conflicting IRQ handler betwwen Serial and Wire when used in Slave Mode

### ISSUE THREAD

**Issue by disk91** [Seeed-Studio/ArduinoCore-samd#54]
When the Wio Terminal is configured as a slave mode, there is a conflicting definition of the IRQ handler:
In variant.h WIRE_IT_HANDLER is defined as SERCOM4 handler whatever the ROLE is. This is used by Wire.cpp included library

In variant.c Depends on ROLE, SERCOM4 is also defined and associated to Serial port1

As a consequence, you can't compile with Wire included when in slave mode.

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

Do you still have this problem now?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
