### ISSUE TITLE
USB CDC with flow control

### ISSUE THREAD

**Issue by marchingband** [Seeed-Studio/ArduinoCore-samd#57]
I am trying to use my XIAO to program an ESP32, but esptool.py requires flow control, it is expecting an FTDI chip.
How can I achieve flow control (NAK, etc), to handle large amounts of data, using one of the USB libraries provided with your Arduino lib?

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

May I ask if you have solved this problem so far?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]

**Comment by marchingband** [comment]
Apologies for not getting back sooner. I was not able to solve it, and found another way to solve for my use case.
