### ISSUE TITLE
xiao samd21 arduino arm64 no bossac

### ISSUE THREAD

**Issue by bm16ton** [Seeed-Studio/ArduinoCore-samd#61]
Hello,
      recently bought 3 different models of xioa, rp2040, nrf51840 and samd21, the first two installed in arduino fine on my arm64 machine including the bossac dependency, but samd21 failed bossac not available for your arch. Kinda weird since all three came from same url/boards package json https://files.seeedstudio.com/arduino/package_seeeduino_boards_index.json  seems likely its a silly mistake/over site hopefully easily remedied

**Comment by matsujirushi** [comment]
same question
https://forum.seeedstudio.com/t/wio-terminal-on-raspberry-pi-5/274948/7

**Comment by matsujirushi** [comment]
workaround
https://forum.arduino.cc/t/bossac-error-on-arm64-for-wio-terminal-seeed-samd-boards/1223908/2

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

Do you still have this problem now?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
