### ISSUE TITLE
Seeeduino 1.8.4 Missing Submodules in Arduino IDE

### ISSUE THREAD

**Issue by senglk** [Seeed-Studio/ArduinoCore-samd#63]
Hello,

On Arduino IDE, I added Seeeduino but when I tried to use the `Seeed Studio XIAO SAMD21` board, the IDE warned of missing header files in libraries. [package_seeeduino_boards_index.json link](https://files.seeedstudio.com/arduino/package_seeeduino_boards_index.json). [File link](https://files.seeedstudio.com/arduino/core/samd/ArduinoCore-samd-1.8.4.tar.bz2). Downgrading to 1.8.3 bypassed this issue.

I've downloaded the [1.8.4 version from github](https://github.com/Seeed-Studio/ArduinoCore-samd/releases/tag/v1.8.4) and folders were missing for the submodules.

Seems like the missing folder contents/headers can be caused by not downloading submodules before upload. Please help update the seeedstudio download link used by board manager download for Seeeduino 1.8.4 with the affected files intact.

Thank you.

For all others seeing this, one option to get your seeeduino working is to clone this repo, use `git submodule update --init --recursive` and copy the affected files to the library, or directly `git clone` the offending repositories to the library, or simply downgrade to 1.8.3.

**Comment by Maxwelltoo** [comment]
Sorry, it was a packaging mistake. The latest release has added the missing files.
Please remove the library and reinstall it.
