### ISSUE TITLE
Wrong assignment of wakeup bits to external interrupts in EnergySaving library (Seeeduino XIAO)

### ISSUE THREAD

**Issue by jonas-koeritz** [Seeed-Studio/ArduinoCore-samd#70]
Inside [EnergySaving::enable_eic_wake](https://github.com/Seeed-Studio/ArduinoCore-samd/blame/3116a04e052e49eedbdbe149876739315a600e9c/libraries/EnergySaving/src/EnergySaving.cpp#L71), there is a switch/case that assigns the input pin number to a WAKEUPENx bit. This function mangles them up in a way that will never wake a Seeeduino XIAO correctly. The WAKEUPENx bits are not mixed up like the function suggests. Waking up from external interrupts start's working as soon as you set the WAKEUPENx bit of the pin used to `::begin()` the EnergySaving calls with.

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

Do you still have this problem now?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
