### ISSUE TITLE
Serial.printf("%f") not working

### ISSUE THREAD

**Issue by matsujirushi** [Seeed-Studio/ArduinoCore-samd#8]
https://stackoverflow.com/questions/12703307/arm-none-eabi-gcc-printing-float-number-using-printf

Maybe need linker option `-u _printf_float -u _scanf_float`.

**Comment by LynnL4** [comment]
This problem has been fixed

**Comment by matsujirushi** [comment]
https://github.com/Seeed-Studio/ArduinoCore-samd/commit/a55f7b599e98d35b2f1d684cc16a1eab14b9e198
